### ISSUE TITLE
Game backlog

### ISSUE THREAD

**Issue by Cosetto** [Dir-A/CMVS-Tools#2]
Since you're fully analyze the cmvs engine, can you also find solution for the backlog?
![image](https://user-images.githubusercontent.com/81801486/192805727-0ed1f943-f772-4f8a-a536-4eae6c93c119.png)

**Comment by Dir-A** [comment]
I have not fully analysed this engine bro.
This looks like a ui bug.
Perhaps the text box has a length  limit or Two text boxes do not adjust adaptively.
Fixing this issue may require reverse analysis of the game's virtual machine code, which is more difficult.

and I've got a lot of experiments going on these days, like an analo circuit experiment and various physics experiments.
Need to process data and submit reports,So I don't have time to deal with this.

You might try adding line breaks to the text, removing automatic line breaks, resizing the font,
or putting excessively long text into the next paragraph of the dialogue to solve this problem.

**Comment by Cosetto** [comment]
Okay so I just found out the intproc.ps3 controls the backlog settings. I used Amatsutsumi English release files on Japanese version and it fixed the backlog, now idk how it will work for Kunado. I think there're byte call function for message_log.pb3 somewhere in intptoc.ps3 just like BGI
