### ISSUE TITLE
PS3TextEditor doesn't work

### ISSUE THREAD

**Issue by linakima** [Dir-A/CMVS-Tools#4]
Game (eng version): https://vndb.org/v18852
I'm trying to create a json file from a .ps3 script.
But the json file is not created.

![1](https://github.com/Dir-A/CMVS-Tools/assets/34077156/dc4f116b-59b7-4cfc-b47b-937d6d4db490)

[files.zip](https://github.com/Dir-A/CMVS-Tools/files/13963013/files.zip)

**Comment by linakima** [comment]
And I can't compile some files.

![2](https://github.com/Dir-A/CMVS-Tools/assets/34077156/d9e753bd-94df-45af-9aaf-a0ea6b527f38)


Can you post a compiled build of the programs?

**Comment by Dir-A** [comment]
The English version doesn't package the files, its ps3 files are encrypted,.
if you use garbro to extract ps3 files from cpz, it will automatically decrypt them.
for now you need to decrypt ps3 files via PS3_Cryptor.exe, then you can edit ps3 files via PS3_TextEditor.exe

If you want to compile the project, you should use x86 first, but the latest commit already allows you to compile via x64, but virtual filesystem related projects will not compile under x64

[release.zip](https://github.com/Dir-A/CMVS_Tools/files/13988977/release.zip)

**Comment by linakima** [comment]
Awesome, thanks!
I only need to change the string with the "tra" key to translate, right? 
PS3_TextEditor and PS3_Cryptor don't support working with folders that store scripts?

![12](https://github.com/Dir-A/CMVS_Tools/assets/34077156/964df9d1-9071-460b-8908-ae6c5f4544d3)
![33](https://github.com/Dir-A/CMVS_Tools/assets/34077156/84278e91-decd-4761-b546-8a7bcc397bb8)

**Comment by Cosetto** [comment]
[ps3_decoder.zip](https://github.com/Dir-A/CMVS_Tools/files/13992281/ps3_decoder.zip)
Drag the folder contains ps3 to that.
Use command **move code\\*.dec ./dec** to move decoded files to other folder
Use command **ren \*.dec \*.** to batch rename to .ps3

You need to make a batch file like this:
![image](https://github.com/Dir-A/CMVS_Tools/assets/81801486/ff98d0fa-e2b1-4aa0-8ab1-28bf1b3a3094)
The tool doesn't work with "for %%i in (code\\*.ps3) do" batch command somehow.

**Comment by linakima** [comment]
@Dir-A 
And I have a question about the codepage for PS3TextEditor.
I'm trying to insert Cyrillic characters 
```
			"raw": "\\\"...Egg...\\\"",
			"tra": "\\\"test test\\n тест тест\\n...Egg...\\\""
```
I used KOI8-R, CP866, CP1251, 65001. But I always got the same result:

![123](https://github.com/Dir-A/CMVS_Tools/assets/34077156/69346556-5255-45b4-8290-3d1a3eb1fea6)

I tried inserting katakana characters into the text

```
			"raw": "\\\"...Egg...\\\"",
			"tra": "\\\"test test\\n ﾕﾇﾔﾕ ﾕﾇﾔﾕ\\n...Egg...\\\""
```
Code pages 936, 932 caused: runtime_error:RxCvt::ToMBCS Error!
Inserting using Codepage 65001 produced the following result:

![11](https://github.com/Dir-A/CMVS_Tools/assets/34077156/31244b49-15d3-4377-9929-7c52b541a269)

The game uses the MS Gothic font.

@Cosetto Thanks!

**Comment by Cosetto** [comment]
It's because his hook set the charset to GBK (936).
Try this
[cmvshook.zip](https://github.com/Dir-A/CMVS_Tools/files/13992572/cmvshook.zip)
version.dll is the hook and also a proxy, so you don't need loader.exe to run it. Just place in same directory as the exe and place all edited .ps3 and .pb3 in "patch" folder.

**Comment by Cosetto** [comment]
[version.zip](https://github.com/Dir-A/CMVS_Tools/files/13992673/version.zip)
Nevermind about the previous version.dll. Use this instead.

**Comment by linakima** [comment]
@Cosetto 
All .ps3 files are already in the Amatsutsumi\data\code folder by default. I didn't have to unpack the archives or use hooks and create a patch folder. The Japanese version probably needed all this. But I use English version.
I just take those files, decrypt them, change the text, encrypt them, and put them back in the original folder. The font can be easily changed in the cmvsConfigNet.exe. 
The version.dll hasn't changed anything. I think the problem is in the code page for converting the json to the ps3.

I can give you [the game](https://pixeldrain.com/u/9qbMAhzt), try changing a text in the file sn1001.ps3
```
		{
			"raw": "\\\"...Egg...\\\\\\\""
			"tra": "Test cyr: гшукащтву Test kata: ゴデビピ"
		},
```

**Comment by linakima** [comment]
utf8, shift-jis doesn't work for me either.
Maybe it's always set to 936

**Comment by linakima** [comment]
I tried to insert Chinese characters
```
{
"raw": "\\\"...Egg...\\\"",
"tra": "春天女士男友"
},
```
codepage 936:
Font - MS Gothic

![123](https://github.com/Dir-A/CMVS_Tools/assets/34077156/6578bdcd-8cc8-42db-820d-8463bd9eaab3)

Something is broken in PS3_TextEditor or PS3_Cryptor
Only English characters are displayed correctly. Looks like I'll have to make  a custom font and change all English characters to other ones.

**Comment by linakima** [comment]
@Cosetto 
I put your version.dll in the English version of Hapymaher. The game does not run in the x32 version.  I unpacked the script.cpz. Converted the files to json, replaced the text, converted back to .ps3, encrypted and put them in the "patch" folder. Nothing has changed, the game does not run.

**Comment by Cosetto** [comment]
Sorry, I compile version.dll with the wrong xor and decompress addresses for Amatsutsumi. It should be this one.
[version.zip](https://github.com/Dir-A/CMVS_Tools/files/13996302/version.zip)
![image](https://github.com/Dir-A/CMVS_Tools/assets/81801486/48828dd8-92e8-4b34-ba2a-16e51ceebfad)

**Comment by Cosetto** [comment]
> I put your version.dll in the English version of Hapymaher. The game does not run in the x32 version.

[Hapymaher.zip](https://github.com/Dir-A/CMVS_Tools/files/13996354/Hapymaher.zip)
Run Juego.bat
![image](https://github.com/Dir-A/CMVS_Tools/assets/81801486/e73a6b18-b39c-4a7a-a6de-6f2a1099eb1b)

**Comment by linakima** [comment]
@Cosetto 
Thank you! All .dll files work fine. 
There are problems with large spaces between characters. But I already made a custom font and it displays fine.
All problems are solved.
