### ISSUE TITLE
PS3文本回封错误

### ISSUE THREAD

**Issue by Ptilopsis01** [Dir-A/CMVS-Tools#5]
请问大佬，把txt重新封回ps3时是有什么要求吗？我直接封回去发现整个ps3的文本都是错乱的，具体表现为用winhex打开的情况下，只在原文本的后面添加了新翻译的文本，且添加的翻译不全，在游戏内也不能正常显示，不是空白就是大段的乱码
[seshun.zip](https://github.com/Dir-A/CMVS_Tools/files/14424618/seshun.zip)

具体文件我这边打包了，fail translation的部分是翻译的问题，不应该影响回封才对啊

**Comment by Dir-A** [comment]
早就改成json导出了，怎么还是txt
请使用最新commit的代码编译
[PS3_TextEditor.zip](https://github.com/Dir-A/CMVS_Tools/files/14430231/PS3_TextEditor.zip)

**Comment by Ptilopsis01** [comment]
> 早就改成json导出了，怎么还是txt 请使用最新commit的代码编译 [PS3_TextEditor.zip](https://github.com/Dir-A/CMVS_Tools/files/14430231/PS3_TextEditor.zip)

这个版本我也试了，会报错`RxCvt::ToMBCS Error!`，试了好几种编码也是一样的情况

**Comment by Dir-A** [comment]
> RxCvt::ToMBCS Error! 

是因为有不能转换成目标编码的字符存在，比如cp936 并不能完整映射所有的cp932的字符

**Comment by Ptilopsis01** [comment]
> > RxCvt::ToMBCS Error!
> 
> 是因为有不能转换成目标编码的字符存在，比如cp936 并不能完整映射所有的cp932的字符

那紫社这个引擎建议用哪种编码注入呢，它能识别utf16么
（而且我即使用932注入也会有这个报错）

**Comment by Dir-A** [comment]
触发异常说明你改了json的编码或者你写了中文而用cp932导入，因为cp932根本不能映射几个中文字符，否则cp932导入是不会触发异常的，不然根本没办法提取出文本来

你用gbk不就好了，把一些不能转换成gbk的字符换掉就行了，比如 ♪ 这个符号，gbk是没有的，所以json的tra下的翻译文本不能使用这个符号

**Comment by Ptilopsis01** [comment]
> 触发异常说明你改了json的编码或者你写了中文而用cp932导入，因为cp932根本不能映射几个中文字符，否则cp932导入是不会触发异常的，不然根本没办法提取出文本来
> 
> 你用gbk不就好了，把一些不能转换成gbk的字符换掉就行了，比如 ♪ 这个符号，gbk是没有的，所以json的tra下的翻译文本不能使用这个符号

感谢大佬，确实可以，真就是这个符号的原因😂
但是我改了start.ps3之后，虽然确实能免封包读取了，但用gbk导入的文本似乎还是会被当做shiftjis读取，显示出来是乱码，这个问题有解决方案嘛

**Comment by Dir-A** [comment]
https://github.com/Galgames-Patch-Fix/Kunado_cn
参考这个项目

**Comment by Ptilopsis01** [comment]
> https://github.com/Galgames-Patch-Fix/Kunado_cn 参考这个项目

这个不是国记的汉化移植嘛，请问编译了一遍之后要用哪些组件啊，没搞明白

**Comment by Dir-A** [comment]
让你看里面的代码，改了啥，看完不就知道怎么搞了

**Comment by Ptilopsis01** [comment]
> 让你看里面的代码，改了啥，看完不就知道怎么搞了

啊我水平不太够，搞不太懂（）

**Comment by Dir-A** [comment]
多补基础，不要瞎搞
